export enum EUrls {
  MAIN = '/',
  LOGIN = '/login',
  REGISTER = '/signUp',
  ABOUT = '/about/',
  CATEGORIES = '/categories',
  PROFILE = '/profile/',
  PROFILE_FAVORITES = '/profile/favorites/',
  PROFILE_RECIPES = '/profile/recipes/',
  CREATE_RECIPE = '/profile/createRecipe',
  UPDATE_RECIPE = '/profile/editRecipe',
  SEARCH = '/search',
  RECIPES = '/recipes/',
  RECIPE = '/recipe',
}
